[package]
name = "viewer"
version = "0.3.0"
edition = "2021"

[dependencies]
eframe = { workspace = true }
egui = { workspace = true }
reqwest = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
anyhow = { workspace = true }
